motd=A Minecraft Server
level-name=world
gamemode=survival
difficulty=easy
pvp=true
max-players=20
online-mode=true
allow-nether=true
enable-command-block=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
generate-structures=true
view-distance=10
white-list=false
server-port=25565
server-ip=
hardcore=false
force-gamemode=false
enable-rcon=false
rcon.password=geheim
